### PR TITLE
build version 0.14.2

### PR DESCRIPTION
**Pull request by sraimund**
I have zipped the osg directory in 'blender-2.5/exporter' to create a new build. I've tested the build in Blender 2.70, 2.72 and 2.73a (Windows 7, 64bit) successfully. This would solve issues #25 and #33 in my opinion.

### CODE REVIEW

**Comment by cedricpinson** [comment]
I would prefer to have code / script to produce a clean package instead of a zip directly. Could you explain how you fixed it ?

**Comment by sraimund** [comment]
I did not change anything in the source code, I just zipped the files in the 'blender-2.5/exporter/osg' directory. I had the same problem as samiujan in issue #33 and this was because I used 'osgexport-0.14.1.zip' in Blender 2.73a from the 'blender-2.5/build/' directory. I did not see that you already created a 'osgexport-0.14.2.zip' in https://github.com/cedricpinson/osgexport/releases, so I assumed  0.14.1 was the latest version of your plugin.

**Comment by alexcham** [comment]
First of all thank you Cedric for you work, nice addon!
And the second is what i have found around the issue "osgexport cannot import name 'osgdata'".
In fiew words: Blender MUST be configured & build with:
-DWITH_PYTHON_INSTALL=ON \
-DWITH_PYTHON=ON \

Below is more detailed overview of the workflow

#) Prerequisites

$ uname -a
Linux local 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

OpenCOLLADA$ git log -1
commit 3335ac164e68b2512a40914b14c74db260e6ff7d
Merge: 220c391 805928b
Author: Rémi Arnaud <remi@acm.org>
Date:   Tue Apr 28 17:18:07 2015 -0700

blender$ git log -1
commit 8299284389fc4992128a15fff5b8269185933827
Author: Campbell Barton <ideasman42@gmail.com>
Date:   Tue May 26 21:36:11 2015 +1000
$ blender --version
Blender 2.74 (sub 5)

osg$ git log -1
commit 57b5747ef44ff8d5a21ca1a5420aa309a7273492
Author: Robert OSFIELD <robert.osfield@gmail.com>
Date:   Thu Jun 4 09:35:19 2015 +0000    
git-svn-id: http://svn.openscenegraph.org/osg/OpenSceneGraph/trunk@14895 16af8721-9629-0410-8352-f15c8da7e697



#) osgexport cannot import name 'osgdata'

B-bug, F-fix

B:
ImportError: cannot import name 'osgdata'
F:
Blender MUST be configured & build with:

-DWITH_PYTHON_INSTALL=ON \
-DWITH_PYTHON=ON \

WITH_PYTHON					        "Enable Embedded Python API  (only disable for development)" ON)
WITH_PYTHON_INSTALL					       "Copy system python into the blender install folder" ON)



#) Download/Install/Enable Addon

https://github.com/cedricpinson/osgexport/releases/download/0.14.2/osgexport-0.14.2.zip



#) Blender import *.X (i.e. *.dae)/Blender export *.osgt



#) View animation

$ osganimationviewer --drawbone /home/alex/Downloads/untitled.osgt

**Comment by sraimund** [comment]
I think the main problem is that people are not using the latest release of the osgexport plugin. In the README of this repository it is stated: 

> Blender 2.5+
> To install last version of the exporter go in user preference, then 'install addons' with the zip from
> https://github.com/cedricpinson/osgexport/tree/master/blender-2.5/build

However the latest version is not included in this directory, that's why I created this pull request.

**Comment by AurL** [comment]
Hi,

I updated the README so that it is now pointing on the release page instead of the `build` directory (which will probably be removed soon)

Anyway, thanks for your PR :)
I am closing it now since it is solved ( but don't hesitate to ping me back here if needed)
